stages:
  - heroku
  - build

build app:
  type: build
  stage: build
  image: node:16
  before_script:
    - yarn install
  script:
    - yarn build

heroku:
  type: deploy
  stage: heroku
  image: ruby:latest
  before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY
  only:
    - master
